name: HTML validate, JS/CSS Linting

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  html-validate:
    uses: groda/gha-workflows/.github/workflows/html-validate.yml@main

  eslint:
    uses: groda/gha-workflows/.github/workflows/eslint.yml@main

  stylelint:
    uses: groda/gha-workflows/.github/workflows/stylelint.yml@main
  